name: Samsung SmartStore CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: samsung-smartstore
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker Image
        run: |
          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            aws ecr get-login-password --region ap-southeast-1 | \
            docker login --username AWS --password-stdin \
            775615218925.dkr.ecr.ap-southeast-1.amazonaws.com

            docker pull \
            775615218925.dkr.ecr.ap-southeast-1.amazonaws.com/samsung-smartstore:latest

            docker stop samsung-smartstore || true
            docker rm samsung-smartstore || true

            docker run -d \
              --name samsung-smartstore \
              --restart unless-stopped \
              -p 5000:5000 \
              -e FLASK_ENV=production \
              -e SECRET_KEY=SamsungSecretKey \
              -v /opt/samsung-smartstores/instance:/app/instance \
              775615218925.dkr.ecr.ap-southeast-1.amazonaws.com/samsung-smartstore:latest

            sleep 10

            curl -f http://127.0.0.1:5000/health